<?php
/**
 * Main constants.
 */

define( 'MAX_MARINE_BACKGROUND_PROCESSOR_PLUGIN_VERSION', '1.0.0' );
define( 'MAX_MARINE_BACKGROUND_PROCESSOR_DATABASE_VERSION', '10' );

define( 'MAX_MARINE_BACKGROUND_PROCESSOR_PLUGIN_PATH', plugin_dir_path( __DIR__ ) );
define( 'MAX_MARINE_BACKGROUND_PROCESSOR_PLUGIN_BASENAME', plugin_basename( __DIR__ ) );
define( 'MAX_MARINE_BACKGROUND_PROCESSOR_PLUGIN_URL', trailingslashit( plugin_dir_url( __DIR__ ) ) );

define( 'MAX_MARINE_BACKGROUND_PROCESSOR_PLUGIN_OPTIONS_KEY', 'MMBP_' );

define( 'MAX_MARINE_BACKGROUND_PROCESSOR_JS_VERSION', '202403201' );
define( 'MAX_MARINE_BACKGROUND_PROCESSOR_CSS_VERSION', '202403201' );
